### ISSUE TITLE
Complex Shape Object

### ISSUE THREAD

**Issue by JonathanHHenson** [CodingRainbow/asteroids-advanced#16]
The ComplexShape object is an entity that contains an array of Shape objects with positions local to the ComplexShape.

Dependencies:
- [ ] The entity class supports hit boxes
- [ ] The Shape object is an entity
- [ ] Shape object support circles
- [ ] Shape primitive objects created: (Circle, Square, Triangle)

Additional Features:
- [ ] Make the Ship object a Triangle
- [ ] Make the Asteroid object a shape
- [ ] Make the Laser object a Circle

**Comment by Limeliz** [comment]
Are we shooting bullets now? I thought we shot lasers, like in sci-fi movies. :D

**Comment by JonathanHHenson** [comment]
Whoops I'll fix that. I wrote this while half asleep
