### ISSUE TITLE
Mobile Compatibility

### ISSUE THREAD

**Issue by JonathanHHenson** [CodingRainbow/asteroids-advanced#24]
Make mobile friendly by:
- [ ] Preventing scrolling (http://stackoverflow.com/questions/16637031/completely-disable-scrolling-of-webpage)
- [ ] Making ship static in centre of screen on mobile site (World rotates rather than ship)
- [ ] Ship thrusts dependent on device tilt
- [ ] Adding touchscreen controls to mobile site:
- - [ ] Ship turns left when left side of screen touched and right when the right side is touched.
- - [ ] Fire laser Button

**Comment by NaveTK** [comment]
I really dislike virtual buttons and pads on a touchscreen tho... I'd rather have some other kind of controls on mobile

**Comment by JonathanHHenson** [comment]
I just took a look at the docs for p5, and we can access the rotation of the mobile device, so we can use that

**Comment by MunWolf** [comment]
I am fine with rotating to steer, the velocity could be touch based but we would still need buttons (maybe only two each at the bottom corners) for toggling the stabilizer and shooting.
